<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://service/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" name="HolidayServiceImplService" targetNamespace="http://service/">
  <wsdl:types>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://service/" elementFormDefault="unqualified" targetNamespace="http://service/" version="1.0">

  <xs:element name="countDaysToHolidays" type="tns:countDaysToHolidays"/>

  <xs:element name="countDaysToHolidaysResponse" type="tns:countDaysToHolidaysResponse"/>

  <xs:complexType name="countDaysToHolidays">
    <xs:sequence/>
  </xs:complexType>

  <xs:complexType name="countDaysToHolidaysResponse">
    <xs:sequence>
      <xs:element minOccurs="0" name="return" type="xs:long"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>
  </wsdl:types>
  <wsdl:message name="countDaysToHolidaysResponse">
    <wsdl:part element="tns:countDaysToHolidaysResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="countDaysToHolidays">
    <wsdl:part element="tns:countDaysToHolidays" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="HolidayService">
    <wsdl:operation name="countDaysToHolidays">
      <wsdl:input message="tns:countDaysToHolidays" name="countDaysToHolidays">
    </wsdl:input>
      <wsdl:output message="tns:countDaysToHolidaysResponse" name="countDaysToHolidaysResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="HolidayServiceImplServiceSoapBinding" type="tns:HolidayService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="countDaysToHolidays">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="countDaysToHolidays">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="countDaysToHolidaysResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="HolidayServiceImplService">
    <wsdl:port binding="tns:HolidayServiceImplServiceSoapBinding" name="HolidayServiceImplPort">
      <soap:address location="http://localhost:8080/soap_service-1/HolidayServiceImpl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>